all:
	@$(MAKE) tests/get_cells/executables -C ../..

t: test
test:
	@$(MAKE) tests/get_cells/tests -C ../..

r: results
results:
	@$(MAKE) tests/get_cells/results -C ../..

c: clean
clean:
	@$(MAKE) tests/get_cells/clean -C ../..

