all:
	@$(MAKE) tests/get_cell_datatype/executables -C ../..

t: test
test:
	@$(MAKE) tests/get_cell_datatype/tests -C ../..

r: results
results:
	@$(MAKE) tests/get_cell_datatype/results -C ../..

c: clean
clean:
	@$(MAKE) tests/get_cell_datatype/clean -C ../..

